export const enum SkipId{
    GO_TO_PERSONAL="GO_TO_PERSONAL",
    GO_TO_EXCHANGE_GOODS="GO_TO_EXCHANGE_GOODS",
    GO_TO_BUY_GOODS="GO_TO_BUY_GOODS",
}

export const enum DataType{
    MATCH="MATCH",
    BET_TYPE="BET_TYPE",
    NORMAL_BET_TYPE_SELECTION="NORMAL_BET_TYPE_SELECTION",
    SPECIAL_BET_TYPE_SELECTION="SPECIAL_BET_TYPE_SELECTION",
}
